version: '3'
services:
  py-sidecar:
    build:
      dockerfile: infra/Dockerfile.py-sidecar
      context: ../
    ports:
      - '9126:9126'
    environment:
      PORT: '9126'
    command:
      python app/app.py
