FROM node:14

RUN mkdir -p /opt/ts-service
WORKDIR /opt/ts-service

ADD package.json .
ADD package-lock.json .

COPY proto/ ./proto
COPY app/ ./app

RUN mkdir -p ./scripts
ADD scripts/gen-ts-pb.sh ./scripts

RUN npm ci
RUN ./scripts/gen-ts-pb.sh
