FROM python:3.9

RUN mkdir -p /opt/py-sidecar/app
WORKDIR /opt/py-sidecar

ADD py-sidecar/app/app.py ./app/
ADD py-sidecar/app/py_package.py ./app/
ADD scripts/gen-py-pb.sh .
ADD py-sidecar/requirements.txt .

COPY proto/ ./proto

RUN pip install -r requirements.txt
RUN ./gen-py-pb.sh ./proto
